
---
- name: Playbook to create a new product role on Satellite
  hosts: localhost
  connection: local
  tasks: 
    - name: Create product role
      redhat.satellite.role:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ sat_url }}"
        name: "{{ role_name }}"
        description: "Repoadmin for {{ product_name }}"
        organizations:
          - "{{ sat_organization }}"
        state: present
        filters:
          - permissions:
              - view_products
              - edit_products
            search: "name = {{ product_name }}"

    #- name: Create user group
    #  redhat.satellite.usergroup:
    #    name: "{{ usergroup_name }}"
    #    admin: false
    #    state: present
        